### ISSUE TITLE
[Enhancement] Apply current theme to RichText control (starting with border color)

### ISSUE THREAD

**Issue by michaelmaillot** [pnp/sp-dev-fx-controls-react#1428]
#### Category
[x] Enhancement

[ ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [3.12.0]

#### Expected / Desired Behavior / Question

When working with the RichText control, we should have the same theme used as the one on the target site.

#### Observed Behavior

Currently, the target site's theme isn't reflected on the RichText control:

![image](https://user-images.githubusercontent.com/44271458/215045968-cc5575a9-c1ce-4d7d-80ed-696e5595031e.png)

#### Steps to Reproduce

* Init a SPFx project which contains the RichText control
* Start local server and display the control on a SharePoint site that has a specific theme (other than the default one)

#### Additional info

Maybe this issue can regroup other improvments regarding control's theme adjustments. I was thinking about #669 for example.

**Comment by michaelmaillot** [comment]
The direct resolution for the border color is to update the `RichText.module.scss` file and to update the `border-color` attribute:

```css
.ql-active .ql-editor:active:hover {
    border-color: '[theme:themePrimary, default:#0078d7]'; // instead of $ms-color-themePrimary
}
```

But there are probably other updates to do in the SASS module.
